### ISSUE TITLE
dte Environment variable

### ISSUE THREAD

**Issue by ericmschmidt** [ironmansoftware/poshtools-issues#1]
I'm currently running v5.3.2 of the PowerShell Tools for Visual Studio extension and have a script that I would run to open files changed between changesets. This script uses the dte environment variable variable that held a reference to the Visual Studio instance. It seems that this variable is no longer defined. Is this from something that changed in your tool?

**Comment by adamdriscoll** [comment]
There haven't been any recent changes to the tool that would cause this but the change from v4-v5 did cause an issue with some folks using the $dte variable. 

You are running PowerShell v5?

**Comment by ericmschmidt** [comment]
According to Get-Host | Select-Object Version, I currently have 5.1.17763.771. When I run the same thing in the PowerShell Interactive Window it returns 1.0.0.0

**Comment by adamdriscoll** [comment]
Sounds like you are using 5.1. You can use $PSVersionTable to check the PS runtime version. I will take a look and see if I can reproduce this issue and get it resolved. I'll let you know if I need more information.

**Comment by adamdriscoll** [comment]
Resolved in next version.
