### ISSUE TITLE
Script Size Limitation when building in VS 2019

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/poshtools-issues#19]
See: https://forums.universaldashboard.io/t/executable-build-error-in-vs-2019-csc-error-cs8103/2359

**Comment by vppetrov** [comment]
We have this issue as well, using VS 2019 16.5.1 in an SQL migration project with relatively a lot of update scripts

**Comment by adamdriscoll** [comment]
@vppetrov - Is there any way you can package the update scripts into a module and then kick them off via a "runner" script. 

I think that might work around this issue. I'll work at fixing this but that might get you going in the mean time.

**Comment by vppetrov** [comment]
I found a workaround for this time but the bug remains in the most recent version of VS 2019.

**Comment by adamdriscoll** [comment]
Cool. Yep. I haven't resolved this. I'll update this issue when it has been.

**Comment by vppetrov** [comment]
Thanks, @adamdriscoll

**Comment by adamdriscoll** [comment]
Fixed in next version.
