### ISSUE TITLE
PSSCRIPTPAD Update downloads same version.

### ISSUE THREAD

**Issue by benconaway** [ironmansoftware/poshtools-issues#23]
PSSCRIPTPAD at version 5.5.1.  States Update Available to version 5.6.0.  Clicking on it downloads version 5.5.1.  Download link in Github also gives version 5.5.1.

**Comment by adamdriscoll** [comment]
We had a snafu with the publishing of the build where the wrong version number was set in the 5.6.0 build. It has the 5.6.0 code but the version number states 5.5.1. This is why it says it needs to update all the time.

**Comment by adamdriscoll** [comment]
Fix in recent versions.
