### ISSUE TITLE
PSSCRIPTPAD cannot use PowerCli modules. The method or operation is not implemented

### ISSUE THREAD

**Issue by benconaway** [ironmansoftware/poshtools-issues#24]
Simple connection script using PowerShell 7 fails in PSSCRIPTPAD but works fine in PowerShell Console.  

Example script:

Import-Module VMware.Powercli
Connect-VIServer test.local

Output:

PS C:\Users\username\Documents>
Exception: C:\Users\username\Documents\test\test.ps1:1
Line |
   1 |  Import-Module VMware.Powercli
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | VMware.VimAutomation.License module is not currently supported on the Core edition of PowerShell.

Connect-VIServer: C:\Users\username\Documents\test\test.ps1:2
Line |
   2 |  connect-VIServer test.local
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The method or operation is not implemented.

PS C:\Users\username\Documents>

**Comment by adamdriscoll** [comment]
This doesn't work for me in PowerShell 7 at all. 

![image](https://user-images.githubusercontent.com/1256531/85163186-b9d9a400-b21f-11ea-9e46-94b45077110b.png)
