### ISSUE TITLE
PS Pro tools is interfering with or suppressing the console window that opens when debugging a console app

### ISSUE THREAD

**Issue by StingyJack** [ironmansoftware/poshtools-issues#26]
After I installed PSPT 5.4.3 (or w/e the latest is as of last week) when debugging any console application (console, webjob, winsvc debug, etc) the actual console is never visible. Visual Studio continues to execute as if it was, but there is no visible window. Checking in task manager, there are instances of conhost.exe being launched each time I debug but they are small memory footprint (56KB or something like that) like a program thats having startup issues will look sometimes. They are not closed when debugging stops. 

Disabling the PSPT extension lets the console windows work again. Re-enabling it allows the console application to display the first time I start to debug, but not again after that. (until I disable it again)

I had no problems using the Powershell Interactive Console during this time, but that was the only PSPT related feature I needed to use. This happened on VS 16.3.9 and 16.5.4 ( I updated VS thinking it was a VS problem). Let me know if you need anything else to troubleshoot this issue. I'll try reinstalling the extension in a few days if I dont hear anything back.

**Comment by adamdriscoll** [comment]
@StingyJack - This is likely a problem with the experimental PS console that was added in 5.4. I'm going to roll back those changes because it's causing unexpected issues for other users as well. This feature needs more time in the oven before releasing it again.

**Comment by adamdriscoll** [comment]
I'm closing this for now as the experimental console has been removed in 5.4.4. I'll ensure that your use-case works if we decide it's ready for release.
