### ISSUE TITLE
Output from script is not shown in any window.

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#28]
Output from scripts never reaches any view, not matter if I use:
 "some text"
 Write-Output "some text" 
 Write-Error "some text"

The only text shown is fx: "The program 'ToolBox-test.ps1: PowerShell Script' has exited with code 0 (0x0)."

Running version 5.4.4 on:
[VS-about.txt](https://github.com/ironmansoftware/poshtools-issues/files/4510838/VS-about.txt)

Noticed that another user, Anthony Missico, has the same problem:
https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017-18561&ssr=false#review-details

I'm not quite sure how long time back this problem has been present, since it is some time since I've debugged Powershell. But my guts feeling is that it has been there for a while, just getting worse and worse. And now totally out of order.

Best regards
Poul

**Comment by adamdriscoll** [comment]
@pju55 - Are you seeing output in the PowerShell Interactive Console? Tools->Other WIndows->PowerShell Interactive?

**Comment by pju55** [comment]
Oops - not quite sure what you mean. I run inside Visual Studio where I'm used to catch the output in output window "View->Output".
![Capture](https://user-images.githubusercontent.com/32414636/79902268-788c6a00-8411-11ea-83fd-71d03444125c.JPG)
Can't find  "Tools->Other WIndows->PowerShell Interactive"...

**Comment by adamdriscoll** [comment]
Sorry about that. I meant View->Other Windows

**Comment by pju55** [comment]
Okie, seems like I get some output in "Powershell Interactive window".
Is that a new feature - I have never used that window...
But I still miss some output. I use a "throw" in my param :
param([switch]$VERBOSE=$false,
      [string]$IniFile=$(throw "-inifile is required."),
      [string]$TOPFOLDER=$(throw "-topfolder is required.")
     )
But the "throw" output is nowhere to be found. Just gets:
![Capture-throw](https://user-images.githubusercontent.com/32414636/79911729-1c314680-8421-11ea-8995-52155e1232ea.JPG)

**Comment by pju55** [comment]
Any comments?

Also have another oddity: When starting VS and open the first solution, I cannot browse the  functions in my script - as shown on Titlebar-1.jpg. I then select File->Recent Projects and Solutions->the same solution as just opened. And then I can browse my functions. So it's not a problem - just a little annoying ;-)
![Titlebar-1](https://user-images.githubusercontent.com/32414636/80354152-a7259d00-8876-11ea-91b1-6a32d15c5d07.JPG)
![Titlebar-2](https://user-images.githubusercontent.com/32414636/80354157-a7259d00-8876-11ea-9ba8-565abf0957ca.JPG)
My PC is a HP Z4 less than a year old with 32GB memory so it should not be too slow.

**Comment by adamdriscoll** [comment]
@pju55 - I'll be releasing a new build today (5.4.5) to fix the issue with the output. You'll see it in the output pane again and terminating errors in both the PowerShell Interactive window as well as the Output window. Please open a new issue for the drop downs. I'll have to look into that.

**Comment by pju55** [comment]
Great, thanks a lot !! :-)
