### ISSUE TITLE
Pacakged Exe returns String Array and not the CustomObject returned by script

### ISSUE THREAD

**Issue by madhupn** [ironmansoftware/poshtools-issues#3]
A script I have returns a PSObject with data returned from various actions performed within the script. Once the script is packaged into Exe, the retuned object is a String array and not PSObject. Is there a way to enforce this?

**Comment by adamdriscoll** [comment]
You'll never be able to return an actual object from an executable. It'll always use STDOUT. You could return JSON or CliXml from the exe if you want to interact with it in PS. 

For example, you could do something like:

Inside EXE

```
$MyCustomObject | ConvertTo-Json
```

Calling Exe

```
$Object = .\script.exe | ConvertFrom-Json
```

**Comment by madhupn** [comment]
Thanks @adamdriscoll , appreciate your response. I will try that out

**Comment by adamdriscoll** [comment]
Sure thing! Feel free to reopen this issue if you have any issues with the solution.
