### ISSUE TITLE
Debugging stop working after using "Stop Debugging" button repeatedly

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#31]
Have a problem with debugging .ps1 scripts.
Starting debugging session stops working after a while. Just gets: "The program 'ToolBox-test.ps1: PowerShell Script' has exited with code 0 (0x0)." in the output window.

Seems the problem can be provoked by:

1. Set a breakpoint
2. Start debugging session and run to the breakpoint
3. Push Visual Studio "Stop Debugging" button.
4. After a number of iterations, the debugger will no longer start the script.

Seems not to be related to a given script

In the attached logfile look for "str Serie->Film". This is the string being output from the script.
Shortly after the last occurrence of the string an exception is thrown. Don't know if it to be expected. But after that I have to restart Visual Studio to make debugging work again.

Best regards 
poul

I can provoke with this code snippet:
`Function SwapString {
    param(
        [parameter(Mandatory=$true, position=0)] [string]$string,
        [parameter(Mandatory=$true, position=1)] [string]$regexp
   )
   $reg="(.*)($regexp)(.*)"
   if ($string -imatch $reg) {
      $newstring   = $string -replace $reg, '$3$2$1'
   } else {
      $newstring=$string
   }
   $newstring
}

"#############################"
$oldstring="Film->Serie"
$str=SwapString $oldstring "->"
"$oldstring => $str"
exit`    <- breakpoint set here

[log.devenv.exe.txt](https://github.com/ironmansoftware/poshtools-issues/files/4552812/log.devenv.exe.txt)

**Comment by adamdriscoll** [comment]
Thanks. I just reproduced this myself. Looking into it.

**Comment by adamdriscoll** [comment]
This has been resolved and will be available in 5.4.6.

**Comment by pju55** [comment]
Wow - I'm impressed - that's fast !
Thanks a lot!
