### ISSUE TITLE
VSCode: extension keeps running Import-Module over and over in integrated terminal

### ISSUE THREAD

**Issue by poshcodebear** [ironmansoftware/poshtools-issues#33]
It doesn't do it all the time, but it seems if I leave VSCode up for a while (days; in this instance, I left it up over the weekend plus some), the extension eventually starts running `Import-Module 'c:\Users\username\.vscode\extensions\ironmansoftware.powershellprotools-5.10.0\out\PowerShellProTools.VSCode.psd1' -ArgumentList @($false)` over and over again.  It'll run it several times (no output and no errors), then wait for a couple hours and do it again.

This last time it did it right in the middle of me issuing git commands, which only caused the command to fail, but could have (maybe) messed up a commit if I'd been in the middle of a commit message:

![image](https://user-images.githubusercontent.com/6439773/80995423-165d3d00-8df3-11ea-950d-e4a8f44ec516.png)

The problem seems to stop after reloading VSCode, but eventually returns.

PowerShell Pro Tools version: 5.10.0
PowerShell (extension) version: 2020.4,0
PowerShell (host) version: seen in both 5.1 and 7.0
VSCode version: 1.44.2 (system setup), but I've seen it for a few months off and on

**Comment by adamdriscoll** [comment]
We're introducing a different way of loading poshtools that won't require the module to be loaded like this. This will be resolved in 5.12.0
