### ISSUE TITLE
Cannot get rid of "Next statement to be executed".

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#34]
Do not know if it is Poshtools or Visual Studio, but it is driving me mad that I cannot figure out how to get rid of "Next statement to be executed" - shown in the attached screedump. No matter where I set/delete breakpoints, the debugger stop at the yellow arrow. Even after deleting all breakpoints, the debugger still breaks at the cursor in the shown line. I can then stop debugging, move the cursor to another source line, start the debugger - and it stops again at the line shown… 
Which is extremely annoying when the yellow arrow is inside a loop.

It seems I can recreate by:
1. Set breakpoint
2. Start debugging
3. When stopped at breakpoint, click "Step over"
4. Click "Stop debugging"
5. Start debugging
6. When stopped at breakpoint, click "Continue"
7. In stead of continuing to next breakpoint, debugger stops a the line where 4) was executed.

And from now the debugger always stops at 4).

The only way I can get rid of it is to restart VS.
Hope you can give me a hint to what to do.

![Annotation 2020-05-06 210346](https://user-images.githubusercontent.com/32414636/81218439-7d8b1500-8fde-11ea-8165-173e22351228.jpg)

**Comment by adamdriscoll** [comment]
This was an issue with PoshTools and has been resolved. The fix will be in build 5.4.8.
