### ISSUE TITLE
Powershell Interactive Window output is interleaved

### ISSUE THREAD

**Issue by MSACATS** [ironmansoftware/poshtools-issues#35]
I'm not sure when this started happening, as I don't install updates that often, but recently I noticed that if I run a script in the interactive window, the output is all messed up and out of order.  E.g. if I expect

Line 1
Line 2

Line 3
Line 4

I may instead get

Line 4Line 2

Line 3
Line 1

**Comment by adamdriscoll** [comment]
This has been resolved and will be in build 5.4.8
