### ISSUE TITLE
Wish: Leave "Automatically update ..." to user chosen value

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#36]
Hi Adam,
I very much like to be in control of when to update any of my software ;-)
So, I would very much appreciate if you did not set the "Automatically update this extension" at every update.
Please leave it as is.

Best regards - and thanks a lot for your great support and fast problem solving.
Poul

**Comment by adamdriscoll** [comment]
Hi Poul,

I don't think that this setting is enforced by PoshTools. I'll do some research but I'm unaware of how this would be changed after upgrade.

**Comment by pju55** [comment]
Hi Adam,
That's OK - don't use too much time on it. I'll just make a habit to check after upgrade.

**Comment by pju55** [comment]
Hmm, looks like I'm hit by "RTFM" :-)
I found [https://www.kunal-chowdhury.com/2016/07/visual-studio-2015-extension-update.html](url)
and now all my extensions are flagged with a warning about automatic updates being disabled.
It goes for all extensions, but that's OK with me. As said, I like to know what's being changed.
Seems not to be any easy way to control it on a per extension base.

**Comment by adamdriscoll** [comment]
Ah, ok. Good info. Thanks! I'll close this issue.
