### ISSUE TITLE
Breakpoint does not break

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#37]
Hi Adam,

Upgrading to 5.4.8 certainly fixed the problem not being able to remove breakpoints.
Now the situation is the other way round. 
Setting breakpoints have no effect. The debugger just skip them. So at the moment I have no debugger.
I have attached the devenv logfile.
And also a logfile created by Visual Studio I guess. Not sure it has anything with this to do. I just see it random at startup.
Best regards
Poul

[log.devenv.exe.zip](https://github.com/ironmansoftware/poshtools-issues/files/4626808/log.devenv.exe.zip)

**Comment by pju55** [comment]
Pretty confused -  suddenly seemed to work ;-)
But, it seems that breakpoints set at outer level of the code works. While breakpoints set inside for instance an if clause do not.
In the below snippet, the breakpoint set in line 19 (pls see attached jpg) works, while those in 8 and 11 do not.

`Function SwapString {
    param(
        [parameter(Mandatory=$true, position=0)] [string]$string,
        [parameter(Mandatory=$true, position=1)] [string]$regexp
   )
   $reg="(.*)($regexp)(.*)"
   if ($string -imatch $reg) {
      $newstring   = $string -replace $reg, '$3$2$1'
      $str="got a match"
   } else {
      $newstring=$string
      $str="no match"

   }
   "$newstring / $str"
}

"#############################"
$oldstring="Film->Serie"
$str=SwapString $oldstring "->"
"$oldstring => $str"
exit`

![Breakpoints 2020-05-14 135545](https://user-images.githubusercontent.com/32414636/81931962-322ec300-95eb-11ea-9ac2-e541f87b0c01.jpg)

**Comment by adamdriscoll** [comment]
I'm having a hard time reproducing this issue.

![image](https://user-images.githubusercontent.com/1256531/82156846-0ace3500-983b-11ea-823f-bfd4125d6ae0.png)

Can you please delete the log file and then reproduce the issue and send me the log file with just the steps you took to reproduce it?

**Comment by pju55** [comment]
Sure :-)

Step by step:
1. Start VS
2. Select solution
3. When solution is open, select the same solution by File->Recent Projects and Solutions. This because my drop downs are missing at initial opening (Issue #30)
4. Click Start -> stopping at breakpoint line 19
5. Click Start -> executing SwapString without stopping and breaking at line 22

Have made a small video from the debugging part.
Maybe it helps a little.
Apologies for cheating a bit. The video is from a later run than the one in the log file. But the only difference is the breakpoint in line 22.

BTW - tried to place a breakpoint at line 7 too - didn't stop there either.

[log.devenv.exe-2020-05-17.zip](https://github.com/ironmansoftware/poshtools-issues/files/4640867/log.devenv.exe-2020-05-17.zip)

**Comment by adamdriscoll** [comment]
Ah, I see the issue. The problem has to do with the indentation of the line. I've fixed the issue and it will be in the next build. I'll release a new version tomorrow.

**Comment by adamdriscoll** [comment]
Thanks for all the help!

**Comment by pju55** [comment]
My pleasure - excellent support!
