### ISSUE TITLE
QuickFix replaces full code line with fix word / Missing

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#45]
Using PSScriptAnalyzer (1.18.3) gives me a couple of problems:
1: detected "'sort 'is an alias of..."
When using QuickFix a line like 
  "$a = $ActorTitles.Item($actor) -split "::" | sort -uniq" 
is replaced by 
 "Sort-Object"
So only the replaced is left behind.

2: detected "Line has trailing whitespace"
No QuickAction. Maybe that's intended - at least the latest fix no longer makes VS crash :-)

[QuickAction 2020.06.02 - 16.23.22.01.zip](https://github.com/ironmansoftware/poshtools-issues/files/4717858/QuickAction.2020.06.02.-.16.23.22.01.zip)

**Comment by adamdriscoll** [comment]
Fixed in next version.
