### ISSUE TITLE
Ternary operator flagged as syntax error.

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#47]
When using a construct like
   $isItFilm=($dir -imatch "\\Film\\") ? $true : $false
I get these errors:

- You must provide a value expression following the '= operator.
- Unexpected token '?' in expression or statement.

Powershell version is set to "Powershell 7 (x64) in options and is also the one used when executing the debugged script.

**Comment by pju55** [comment]
A follow-up: seems that more (none?) of the new operators are accepted as valid.
Tried more of the stuff from
[https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-70?view=powershell-7](url)
and they failed, too.

**Comment by adamdriscoll** [comment]
This has been fixed in 5.5.4
