### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by changop** [ironmansoftware/poshtools-issues#48]
After poshtools pro updated on 30-May, I now received "There were build errors. Would you like to continue and run the last successful build?" - If I hit yes, it will launch the last build successfully, but I assume any changes I make won't stick.

When I click Yes to revert, i get this error:

![image](https://user-images.githubusercontent.com/35578270/83560335-adddaa80-a4db-11ea-9d37-bb9a2c25d8aa.png)

Line 5 of PowerShellProTools.targets is:  <PowerShellPackageTask PackageEntryPoint="$(PackageEntryPoint)"

Visual Studio 15.9.23
PowerShell Pro Tools 5.5.0

**Comment by adamdriscoll** [comment]
This has been resolved and will be in 5.5.1. I'll push the release shortly.
