### ISSUE TITLE
Selecting "Reset PowerShell Session" breaks script execution/debugging

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#49]
After selecting "Reset PowerShell Session" under "Options->PowerShell Tools", debugger doesn't work. 
The Output windows shows "The program 'debug-test.ps1: PowerShell Script' has exited with code 0 (0x0).", but no code is executed.
"PowerShell Interactive Window" show no output.

Clearing the flag makes debugger work again

Not quite sure what is is meant for - just trying it out.
Up front looks pretty much like something I would appreciate - getting a clean environment in each session.

[log.devenv.exe.txt](https://github.com/ironmansoftware/poshtools-issues/files/4730032/log.devenv.exe.txt)

**Comment by adamdriscoll** [comment]
Thanks for filing this. If you want to reset the PS session without restarting VS, you should be able to select the PowerShell version from the version selector on the toolbar. Even if you select the same version, it will restart PS.

**Comment by pju55** [comment]
Glad you take it from the positive side:-)

Thanks for the hint - forced me into finding the PowerShell toolbar - nice!.
Now I just need to figure out how to make the selected version visible - I can select via the drop-down, but the version window stays blank. 

<img width="257" alt="2020-06-04 16_15_12-Copy_Misc - Microsoft Visual Studio" src="https://user-images.githubusercontent.com/32414636/83768126-b28e9400-a67e-11ea-835f-2a42e320f1be.png">

**Comment by adamdriscoll** [comment]
@pju55 - How important is this reset PowerShell Session functionality to you? We just removed this for now because it was totally broken. We can reimplement this correctly or we could add something manual like a button to reset it.

**Comment by pju55** [comment]
@adamdriscoll - Not important. I would prioritize to get the selected powershell version visible (as mentioned above).
As I understand it, I'll can get the reset this way.

**Comment by pju55** [comment]
Thanks for the fix to the powertools bar - working nicely now.
Small thing - but still nice to have.
Let's close this one.
