### ISSUE TITLE
Losing Settings on several Objects

### ISSUE THREAD

**Issue by MacVille** [ironmansoftware/poshtools-issues#57]
The Following Objects Losing defined Settings:

1. TreeView
2. ContextMenuStrip

After configuring those two Objects and Saving the Settings, the Form will not show the Result.
After open the Powershell Script on PSScriptPad the Settings are completly missing.
Also on the Designer.ps1 the settings are missing again.

**Comment by adamdriscoll** [comment]
Fixed in 5.6.4
