### ISSUE TITLE
Service executable ignoring parameters 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/poshtools-issues#6]
https://forums.universaldashboard.io/t/windows-service-is-ignoring-passed-parameters/2200/2

**Comment by wsmelton** [comment]
Tested this on a new Script project and the debugger does not seem to want to attach either. 

Just created a `PowerShellProject.ps1` and added this code with a breakpoint on line 6:

```
[cmdletbinding()]
param(
	$i
)
foreach ($i in $list) {
	(Get-Process)[$i]
}
```

Hitting F5 or starting the debugger it just flashes open and then closes in VS for some reason. I've enabled diagnostics, but I do not find where that data is being written.

**Comment by adamdriscoll** [comment]
You will now have access to both $ProcessArgs and $ServiceArgs to receive both the process parameters and the service start parameters.
