### ISSUE TITLE
Local variables not accessible in debug session.

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#60]
Just upgraded to 5.5.2  and now the "Locals" window is empty, ie. showing no variables.
Putting a variable into the "Watch" window just give: "Unable to evaluate the expression. Operation not supported. Unknown error: 0x80070057."
Breakpoints works fine, but still no variable values are available.
No logfile is written in  %appdata%\PowerShell Tools for Visual Studio" although enabled in Options.
Have tried to run as administrator and have cleared MEF cache without luck.

Unfortunately I did not save the 5.5.0 .vsix file so I cannot check if it is the upgrade or something else.
Maybe I could get a pointer to it?
Think I'll make a habit out of downloading the .vsix file - not the first time an update has broke something - that's the nature of software:-)
Best regards
Poul

BTW: debugging in Visual Studio Code works fine.

**Comment by adamdriscoll** [comment]
I'll get a fix for this out today. Builds are stored here: https://poshtools.z21.web.core.windows.net/

**Comment by pju55** [comment]
Super. Thanks a lot. For both :-)

**Comment by adamdriscoll** [comment]
The latest version should fix this.
