### ISSUE TITLE
How to enable/disable analysis rules.

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#61]
Not quite sure why #46 was closed.
Can se it's labeled "bug/next-version" but at the same time closed.
The problem is, as shown in #46 , still present for me.

**Comment by adamdriscoll** [comment]
Sorry about that. That was a mistake on my part but I will be looking into it.

**Comment by pju55** [comment]
No problem. Sounds good, thanks. 👍 
Guess this one should closed, then :-)
