### ISSUE TITLE
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part “PowerShellTools.Service.AnalysisWatcher”

### ISSUE THREAD

**Issue by i-gonch** [ironmansoftware/poshtools-issues#63]
After last update of Visual Studio IDE I have the following error when opening my solution:

A MEF Component threw an exception at runtime: Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part “PowerShellTools.Service.AnalysisWatcher”. —> System.ArgumentException: The directory name D:\SLA\SLAssessmentCore\SLAssessmentCore\Core\SLA.Core.Log is invalid.at System.IO.FileSystemWatcher…ctor(String path, String filter)at XmlTestAdapter.EventWatchers.TestFilesUpdateWatcher.AddWatch(String path)at PowerShellTools.Service.AnalysisWatcher.UpdateFileWatcher(IEnumerable`1 files, Boolean isAdd)at PowerShellTools.Service.AnalysisWatcher…ctor(ISolutionProvider solutionProvider, ISolutionEventsListener solutionListener, ITestFilesUpdateWatcher testFilesUpdateWatcher, ITestFileAddRemoveListener testFilesAddRemoveListener)— End of inner exception stack trace —at 
[ActivityLog.zip](https://github.com/ironmansoftware/poshtools-issues/files/4936787/ActivityLog.zip)

Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()

The directory D:\SLA\SLAssessmentCore\SLAssessmentCore\Core\SLA.Core.Log doesn’t exist on disk. If I create the affected directory and restart VS the problem is being resolved.

**Comment by adamdriscoll** [comment]
Fixed in next version.
