### ISSUE TITLE
No syntax check after upgrading to version 5.5.5

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#69]
Seems like 5.5.5 is a bit too effective - as a matter of fact I no longer get any syntax check.
I have attached two jpg's showing the same codesnippet with the 2 versions.
BTW: Still haven't figured out where logging goes (if any) - been away for some time now.

Version 5.5.4:
![Version 5 5 4](https://user-images.githubusercontent.com/32414636/91337151-3b772080-e7d3-11ea-9d67-e4b3ed270174.jpg)
Version 5.5.5:
![Version 5 5 5](https://user-images.githubusercontent.com/32414636/91337148-3ade8a00-e7d3-11ea-98e1-fd7ce2b504b4.jpg)

**Comment by pju55** [comment]
Any hope to se a fix to this? 
This one + issue #58 makes the value of poshtools quite a bit smaller.

**Comment by adamdriscoll** [comment]
@pju55 Sorry for the delay. I've fixed this issue along with #58. It will be coming out in 5.6.2

![image](https://user-images.githubusercontent.com/1256531/93940345-8eb49400-fce9-11ea-92d8-48704a3b0943.png)
