### ISSUE TITLE
Allow preventing a service from starting

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/poshtools-issues#7]
Currently, the service host is suppressing any errors in OnStart and OnStop. It may be desirable to prevent a service from starting if there is an error. We should change how this behaves. 

https://forums.universaldashboard.io/t/how-to-stop-a-ps-service-that-has-onstart-errors/2208

**Comment by banyula** [comment]
Do you have an ETA for solving this?

VICTOR

**Comment by adamdriscoll** [comment]
@banyula - This has been implemented. Both OnStart and OnStop will have access to the ServiceBase class through the $Service variable that will now be available. 

I'm planning for a release tomorrow.
