### ISSUE TITLE
Line numbers offset by one in error list

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#70]
All line numbers are offset by +1 in error list.
Poshtools 5.6.2.
![image](https://user-images.githubusercontent.com/32414636/94272997-244b6000-ff44-11ea-86d1-867f7a6e8f35.png)

**Comment by adamdriscoll** [comment]
Hmm weird. I do not see this issue. I haven't tried on such a large file though.

**Comment by pju55** [comment]
You can have my .psm1 file if you want.
Wonder if it's related to regional settings. Starting at zero or at one...


fre. 25. sep. 2020 17.49 skrev Adam Driscoll <notifications@github.com>:

**Comment by pju55** [comment]
Add-on - it doesn't matter how big the script is.
I just made one with 1 line - and the error list says the error is in line 2.

**Comment by adamdriscoll** [comment]
Resolved in 5.6.4
