### ISSUE TITLE
Better variable expansion of collection in debugger

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#73]
Not sure if this is a bug or an enhancement request. And don't know either if it's a Visual Studio or a Poshtool thing.
Anyway: I use module PsIni (https://www.powershellgallery.com/packages/PsIni/2.0.0) to read from .ini-files.
And VS "Locals" window is not very helpful showing the content of the collection returned from the module.
Visual Studio Code is far more generous expanding the collection recursively. And shows content as string while VS (if showing anything) shows a string as a number of chars.
Would be very nice if VS did a better job in expanding this type of collection.

[test.zip](https://github.com/ironmansoftware/poshtools-issues/files/5317009/test.zip)

**Comment by pju55** [comment]
Seems to be the same problem with xml documents:
    [xml]$fileContents = Get-Content -LiteralPath $xml_path
![XMLDoc-1](https://user-images.githubusercontent.com/32414636/95011709-f8f6fe00-0632-11eb-9150-9fda6c4f81fc.jpg)
![XMLDoc-2](https://user-images.githubusercontent.com/32414636/95011707-f85e6780-0632-11eb-9bd1-9dc7784b7623.jpg)

**Comment by adamdriscoll** [comment]
I've been looking at this today. Here's an example of the XML output. 

![image](https://user-images.githubusercontent.com/1256531/100683117-e9471d80-3334-11eb-88bc-bf44053b80a0.png)

Here's an example of the INI output. 

![image](https://user-images.githubusercontent.com/1256531/100683160-ffed7480-3334-11eb-8f1f-75f79e2655a1.png)

This will be in 5.7.12.

**Comment by pju55** [comment]
@adamdriscoll 
Nice, very nice! Thanks a lot.
