### ISSUE TITLE
Issue package module with Exe

### ISSUE THREAD

**Issue by rdbartram** [ironmansoftware/poshtools-issues#74]
I have two issues packaging a specific module with the merge-script command.

1. The whole module isn't packaged. That is to say there are files missing
2. The module has a dependency on System.Management.Automation.dll which prevents compile

``` script.ps1
import-module pslitedb

New-LiteDBDatabase -Path ./test.db
Open-LiteDBConnection -Database ./test.db

New-LiteDBCollection -Collection SvcCollection

Get-Service b* |
  select @{Name="_id";E={$_.Name}},DisplayName,Status,StartType |
      ConvertTo-LiteDbBSON |
         Add-LiteDBDocument -Collection SvcCollection
```

This script will initially fail to compile. If I just remove the System.Management.Automation.dll from the pslitedb module folder, then the compile completes and the modules is loaded and works. That is except for the ConvertTo-LiteDbBSON command as it is within a psm1 file in the root of the folder, but the rest of module is a compiled binary. Seemingly, there is some discovery going on that sees the dll and copies only that and its dependencies. I've tried changing the psd1 file to see if I can get it to copy over but I can't. I keep thinking I should move away from this module but its just too easy using nosql on ps this way.

I can deal with the duplicated System.Management.Automation.dll problem, but the lack of packaging all files in the module folder is a bit of a nuisance.

Thanks for your help here!

**Comment by adamdriscoll** [comment]
This will be resolved in the next version. I'll get it out today. The problem was that we were using the Path parameter rather than the ModuleBase parameter to determine the root of the module which since the LiteDB module was setup to have the LiteDB.dll in a nested folder would ignore the PSD1 and PSM1 files. I've also added some logic to skip copying SMA.dll if it's found in a module.

**Comment by rdbartram** [comment]
in which command was I using the path parameter and not modulebase?

**Comment by adamdriscoll** [comment]
It wasn't you. It was internally in PoshTools.
